### ISSUE TITLE
Fix eimage FITS headers so that processEimage.py can process them

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/imSim#13]

**Comment by SimonKrughoff** [comment]
Can you fill me in on the problem?  I haven't had problems processing eimages so far with v3.4.  Is this new with v3.5?  We may need to fix things up in obs_lsstSim with v3.5.

**Comment by jchiang87** [comment]
These are eimages produced by the imSim/sims_GalSimInterface code, i.e., from the `imsim.py` code in this package.  I can run `ingestSimImages.py` on them, but when I run `processEimage.py` the task crashes in a somewhat obscure way.  When I add missing header keywords from the corresponding phosim-produced eimage for that visit, `processEimage.py` runs fine, and the outputs look reasonable.  I'm attaching a text file with a dump of the header keywords from `imsim.py`:
[imsim_eimage_header.txt](https://github.com/DarkEnergyScienceCollaboration/imSim/files/544705/imsim_eimage_header.txt)
If you can point me to the code in `obs_lsstSim` that looks at the eimage header, I can narrow down what keywords are needed, or if there is a list somewhere to point at, that would be even better.

**Comment by danielsf** [comment]
@jchiang87 What keywords did you end up having to add?

Simon and I iterated on this about a year ago and I thought we got sims_GalSimInterface to a point where it produced a header like `processCCD` was expecting.

**Comment by SimonKrughoff** [comment]
Also, @jchiang87 if you post the traceback, it might help me figure out what the issue is.

**Comment by jchiang87** [comment]
@danielsf I copied over all of them.  @SimonKrughoff Here's a log of the task output for an un-hacked file, with the traceback of the failure:

[l2_imsim_orig_header.txt](https://github.com/DarkEnergyScienceCollaboration/imSim/files/544886/l2_imsim_orig_header.txt)

**Comment by jchiang87** [comment]
Thanks @SimonKrughoff. `FILTER` is indeed the missing keyword that `processEImage.py` wants.  I must not have run `ingestSimImages.py` directly on the imsim file and just replaced the symlink from when I ran on the phosim file first.

@danielsf Any advice on how to proceed with this?  I guess ultimately the fix has to go into the sims_GalSimInterface code, but if there is some code I can put in imSim temporarily without having to post-process the file, that would be good. I don't see how to do it though.  It seems like it could go in just before [here](https://github.com/DarkEnergyScienceCollaboration/imSim/blob/master/bin/imsim.py#L142)

**Comment by cwwalter** [comment]
You could also monkey patch another function if you have to...

**Comment by jchiang87** [comment]
I don't even see where the FITS keywords are set in the sims code....

**Comment by cwwalter** [comment]
I think it is at line 149 here:

https://github.com/lsst/sims_GalSimInterface/blob/master/python/lsst/sims/GalSimInterface/galSimDetector.py

**Comment by jchiang87** [comment]
Interesting.  That code doesn't seem to be called *anywhere* in the lsst org:
https://github.com/search?q=org%3Alsst+_writeHeader&type=Code

**Comment by danielsf** [comment]
I believe that is code that should be called by GalSim behind the scenes.  I'm pretty sure I wrote `GalSim_afw_TanSipWCS` to comport with GalSim's WCS conventions.  I could be wrong, though.

**Comment by SimonKrughoff** [comment]
The FILTER keyword should be set here: https://github.com/lsst/sims_GalSimInterface/blob/master/python/lsst/sims/GalSimInterface/galSimDetector.py#L64
but there are a couple of checks that mean that it may not be.  Is it possible that the filter is not set to a value the system knows about?

**Comment by jchiang87** [comment]
I see the problem now.  The bandpass is being passed to the ObservationMetaData constructor in a list
https://github.com/DarkEnergyScienceCollaboration/imSim/blob/363e7a7673af95dae4b7d1193ac26af62fbba16a/bin/imsim.py#L97

**Comment by jchiang87** [comment]
Wasn't sure why it was being done that way, but that's an easy fix.  Thanks @SimonKrughoff

**Comment by SimonKrughoff** [comment]
Looks like all three of those parameters should probably be scalars rather than lists.

**Comment by jchiang87** [comment]
yep

**Comment by SimonKrughoff** [comment]
👍

**Comment by cwwalter** [comment]
Hmm... the reason they are in a list is that I found the examples done that way.  See for example:

https://github.com/lsst/sims_GalSimInterface/blob/master/examples/scripts/galSimStarsWithNoise.py#L40

I reduced them down to one band but kept them in a list.

**Comment by SimonKrughoff** [comment]
Maybe the thing to do is to have an ObservationMetadata and an ObservationMetadataList to clear up this ambiguity.

**Comment by jchiang87** [comment]
closed by #4
