### ISSUE TITLE
On Macs running El Capitan and Sierra System Integrity Protection strips relevant LSST environment variables if running as an executable

### ISSUE THREAD

**Issue by cwwalter** [DarkEnergyScienceCollaboration/imSim#18]
On OS X SIP strips out LIBRARY_PATH related environment variables.  This destroys the EUPS based setup system.

In practice for imSim this means this works:

`python bin/imsim.py tests/tiny_instcat.txt`

but this

`bin/imsim.py tests/tiny_instcat.txt`

does not.

This is due to the fact that the script starts with 

`#!/usr/bin/env python`

Instead of the actual relevant python binary we want to use.

@timj has written a DM tech note describing this issue and solutions here:

http://dmtn-001.lsst.io/en/master/

We can either just always run explicitly with python on Mac and make sure this is well documented, or we could apply the DM solution which is to start with a bin.src directory and then have an installation procedure which rewrites the shebang and copies the new binary to "bin".

**Comment by jchiang87** [comment]
I think we should do the `bin.src` thing.  I can look into that.  I'd also like to set up this repo on travis-ci as well as Jenkins (hosted at SLAC), so I'd like to roll out that CI stuff and this `bin.src` thing in a single PR.  If there are any other similar infrastructure things we should address it would be good to include them as well.  We can epic this work to track the progress and maybe divide up the work, if desired.

**Comment by cwwalter** [comment]
I'm not an expert in CI.  Why would you need both Travis and Jenkins?

**Comment by jchiang87** [comment]
We don't really, but we are still evaluating travis vs Jenkins and it would be good to have a few different repositories that have a lot of active development on them in order to make that assessment, and I am assuming this repo will continue to be one of those in the next few months at least.

**Comment by jchiang87** [comment]
One issue that comes up for Twinkles is that some of the catsim-dependent tests need UW database access, and we can only really do that on the SLAC Jenkins platform.  Travis has its relative advantages as well.

**Comment by danielsf** [comment]
In the CatSim unit tests we handle Jenkins' inability to access fatboy by writing utility methods that create local databases that look like fatboy (i.e. same schema).  We could do that for unit tests in Twinkles and ImSim, if we so desire.

**Comment by jchiang87** [comment]
closed by #24
