### ISSUE TITLE
Connect the imSim repo to travis-ci and Jenkins

### ISSUE THREAD

**Issue by jchiang87** [DarkEnergyScienceCollaboration/imSim#20]

**Comment by SimonKrughoff** [comment]
@jchiang87 are you expecting to get resources for this from the project Jenkings, or do you have another Jenkins instance you can use at SLAC or elsewhere?

**Comment by jchiang87** [comment]
@SimonKrughoff I'm planning to use the Jenkins server at SLAC.

@cwwalter I'll need you as an admin to set up the web hooks for both services.  I'll post instructions shortly.

**Comment by cwwalter** [comment]
OK, I understand.  If necessary tell me what to do and I can also add you as an (owner?) on this repo.

**Comment by jchiang87** [comment]
If you could add me as owner, that would be useful.

**Comment by cwwalter** [comment]
OK I have to runout for a bit now.  Will do when I return.

**Comment by jchiang87** [comment]
This is done.  The Jenkins builds are here:

http://srs.slac.stanford.edu/hudson/view/LSST/job/imSim/

and the travis-ci ones here:

https://travis-ci.org/DarkEnergyScienceCollaboration/imSim

**Comment by jchiang87** [comment]
closed by #24
