### ISSUE TITLE
Check for python 3 compatibility.

### ISSUE THREAD

**Issue by cwwalter** [DarkEnergyScienceCollaboration/imSim#27]
Seeing GalSim GitHub email today reminded me of this...

**Comment by jchiang87** [comment]
I already put the python 3 compatibility checks in our CI builds,

https://github.com/DarkEnergyScienceCollaboration/imSim/blob/issue/21/computing_infrastructure/.travis.yml#L26

The outcome is recorded at the travis-ci builds, and if there are incompatibilities, the build will fail:

https://travis-ci.org/DarkEnergyScienceCollaboration/imSim/builds/171564061

Similarly for Jenkins

http://srs.slac.stanford.edu/hudson/view/LSST/job/imSim/10/console

**Comment by cwwalter** [comment]
OK, I see thanks.  I didn't appreciate it was done with a linter.  I will close this.
